config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :performances, only: %i[index show new create] do
    resources :tips, only: %i[new create]
    resources :messages, only: %i[create]
  end

  resources :tips, only: :show do
    resources :payments, only: :new
  end

  resources :artists, only: %i[new create show]
  namespace :artist do
    resources :performances, only: %i[index show]
  end

end

app/views/shared/_artist_performance_avatar.html.erb
<!-- position relative square -->
<div class="wireframe ro-button-useroptions-outer-container" style="display: block;">
  <!-- position fixed square -->
  <div class="wireframe ro-button-useroptions-inner-container">
    <% if @performance.artist.photo.attached? %>
      <%= cl_image_tag @performance.artist.photo.key, class: "ro-button-useroptions-avatar" %>
    <% else %>
      <div class="ro-navbar__user-login-icon-container">
        <i class="fas fa-user ro-navbar__user-login-icon" style=""></i>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_bigbutton.html.erb
<% if params[:controller] == "performances" && params[:action] == "show" %>
  <div data-controller="tip-popup">
    <div data-action="click->tip-popup#toggle" class="ro-button-bigbutton-icon-container wireframe">
      <i class="ro-button-bigbutton-tip-icon">tip</i>
    </div>
    <div class="mt-4 tipping-form" data-tip-popup-target="form">
      <h2 class="my-5 center">How much?</h2>
      <%= render 'tips/form' %>
    </div>
  </div>
<% else %>
  <%
=begin %>
  <%= link_to action_link, class: "#{display_class} ro-button-bigbutton-icon-container wireframe", style: ""  do %>
    <i class="fas fa-qrcode ro-button-bigbutton-qrscan-icon"></i>
  <% end %>
  <%
=end %>
<% end %>

app/views/shared/_brand_logo_button.html.erb
<!-- brand home -->
<div style="ro-button-brand-icon-outer-container wireframe">
  <div class="<%= display_class %> ro-button-brand-icon-container wireframe">
    <%= link_to "/", class: "wireframe", style: "" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="ro-button-brand-icon wireframe"  preserveAspectRatio="none" style="" viewBox="0 0 132.29167 132.29167">
        <path d="m 87.657207,119.94579 c -3.529739,-0.36163 -3.822959,-1.17337 -4.724799,-13.07999 -1.54687,-20.422452 -3.51572,-27.5184 -8.2599,-29.769648 -1.50404,-0.713707 -5.34805,-1.442581 -10.04971,-1.905571 -2.27847,-0.224357 -4.65383,-0.472977 -5.27857,-0.552467 l -1.1359,-0.144537 v -7.545138 -7.545138 l 4.88574,-0.331707 c 11.5966,-0.787347 14.8435,-2.675615 17.041,-9.910363 0.5338,-1.757401 0.58061,-2.337198 0.4418,-5.47225 -0.16457,-3.716969 -0.6285,-5.915287 -1.66762,-7.901955 -2.15584,-4.121706 -5.667,-5.56961 -16.62506,-6.855711 l -4.07586,-0.478367 V 20.85354 13.254122 l 8.48581,0.14504 c 9.69787,0.16576 10.74944,0.32097 14.63049,2.159428 3.289,1.558001 5.18239,2.832725 7.56799,5.09516 4.427392,4.198799 7.155638,9.903636 8.09689,16.930774 0.45374,3.387512 0.147942,9.320969 -0.688255,13.353695 -1.149152,5.54209 -2.454944,8.364632 -5.921214,12.798898 l -2.013611,2.575925 0.824719,1.099884 c 2.043423,2.725195 3.760177,5.22896 4.54604,6.630104 1.871781,3.337179 3.058924,8.194162 3.874389,15.85122 0.979894,9.201016 1.808511,23.73736 1.565661,27.46631 -0.137229,2.10695 -0.20937,2.35458 -0.716008,2.45754 -1.025763,0.20846 -9.085871,0.30372 -10.804022,0.12769 z"/>
        <path d="m 37.056148,119.94731 c -2.57038,-0.35303 -3.06868,-0.59957 -3.30761,-1.63652 -0.25362,-1.10075 -0.50051,-99.740408 -0.25726,-102.78387 l 0.17624,-2.204968 h 7.82952 7.82951 l 0.186331,8.886672 c 0.237839,11.343234 0.0165,95.188486 -0.25437,96.369436 -0.13754,0.5996 -0.431511,0.98194 -0.90549,1.17765 -0.902851,0.3728 -8.980131,0.50979 -11.296871,0.1916 z" />
      </svg>
    <% end %>
  </div>
</div>

app/views/shared/_currently_playing_display.html.erb
<% if @performance.start_time < DateTime.now && @performance.end_time > DateTime.now %>
  <% live_indicator_display = "block" %>
<% else %>
  <% live_indicator_display = "none" %>
<% end %>
<% songs = ["チョコレートインパクト", "Majestic Paradise", "最高のペンギン"] %>
<div class="performance-show-navbar__outer_container wireframe" style="">
  <div class="performance-show_navbar__inner_container" style="">
    <p class="performance-show_navbar__text wireframe" style="margin-bottom: 0px; margin-left: 10px; width: 100%; display; inline-block;"><%= @performance.artist.name %> </p>
    <p class="performance-show_navbar__text wireframe" style="margin-bottom: 0px; margin-left: 10px; width: 100%;">Currently playing: <span class="performance-nav__song-title song-title-fade-in" id="song_title_live_display"><%= songs.sample %></span></p>
  </div>
  <div>
    <span class="live-container" style="display: <%= live_indicator_display %>; align-self: end;">live </span>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_go_button.html.erb
<!-- go -->
<div class="ro-button-h2text-sized-outer-outer-container" style="">
  <div style="ro-button-h2text-sized-outer-container wireframe" style="">
    <div class="ro-button-go-icon-container wireframe">
      <%= link_to performances_path, class: "ro-button-go-icon-container wireframe", style: ""  do %>
        <i class="<%= "fas fa-chevron-right ro-button-standard-go-icon" %>"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_info_window.html.erb
<%= link_to performance_path(performance.id) do %>
  <div class="wireframe">
    <% if performance.artist.photo.attached? %>
      <%= cl_image_tag performance.artist.photo.key, class:"avatar-large" %>
    <% else %>
      <%= image_tag "blank-profile-picture.png", class:"avatar-large" %>
    <% end %>
  </div>
  <div class="wireframe">
    <h2 class="info-window__performance-name"><%= performance.name %></h2>
    <p class="info-window__performance-name"><%= performance.address %></p>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_nav-bottom_bar.html.erb
<div class="fixed-bottom bottom-bar" style="z-index: 50;">
  <div class="navbar navbar-expand-sm navbar-light wireframe" style="padding-left: 0px; padding-right: 0px;">
    <div class="ro-container wireframe" style="overflow: visible; z-index: 80;">
      <!-- user options - hidden from top nav on small screens, shown on bottom nav on small screens -->
      <%= render partial: 'shared/user_options_button', locals: {:display_class => "bottom-nav-icons", :drop_button_id => "useroptions-dropup", :drop_menu_id => "useroptions-dropup-menu"} %>
      <!--tip button - shown on bottom nav on small screens -->
      <%= render 'shared/bigbutton', display_class: "bottom-nav-icons" %>
      <!-- home - shown on bottom nav on small screens -->
      <%= render 'shared/brand_logo_button', display_class: "bottom-nav-icons" %>
    </div>
  </div>
</div>

app/views/shared/_nav-top_bar.html.erb
<% if params[:controller] == "performances" && params[:action] == "show" %>
  <div class="fixed-top top-bar wireframe black_background" style="">
    <!-- background opacity shifting rectangle -->
    <div id="test" class="navbar-background" style=""></div>
    <div class="ro-container wireframe" style="">
      <!-- artist avatar - hidden from top nav on small screens -->
      <%= render partial: 'shared/artist_performance_avatar' %>
      <!-- Currently playing text-->
      <%= render partial: 'shared/currently_playing_display' %>
      <!-- user options  - hidden from top nav on small screens -->
      <%= render partial: 'shared/user_options_button', locals: {:display_class => "wide-screen-buttons", :drop_button_id => "useroptions-dropdown", :drop_menu_id => "useroptions-dropdown-menu"} %>
    </div>
  </div>
<% else %>
  <div class="fixed-top top-bar wireframe" style="">
    <!-- background opacity shifting rectangle -->
    <div id="test" class="navbar-background" style=""></div>
    <div class="ro-container wireframe" style="">
      <!-- brand home - hidden from top nav on small screens -->
      <%= render 'shared/brand_logo_button', display_class: "wide-screen-buttons", style: "z-index: 200;"%>
      <!-- Raibuon search bar -->
      <%= render 'shared/searchbar', display_class: "" %>
      <!-- user options - hidden from top nav on small screens -->
      <%= render partial: 'shared/user_options_button', locals: {:display_class => "wide-screen-buttons", :drop_button_id => "useroptions-dropdown", :drop_menu_id => "useroptions-dropdown-menu"} %>
    </div>
  </div>
<% end %>

app/views/shared/_qr_button.html.erb
<!-- qr scan -->
<div style="ro-button-standard-icon-outer-container wireframe">
  <div class="<%= display_class %> ro-button-standard-icon-container wireframe">
    <%= link_to "https://qrcodescan.in/", class: "#{display_class} ro-button-standard-icon-container wireframe", style: ""  do %>
      <i class="<%= "fas fa-qrcode ro-button-standard-qrscan-icon" %>"></i>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
 <!-- Raibuon search bar -->
<div class="wireframe searchbar-main <%= display_class %>" style="z-index: 99; position: relative;">
  <%= form_tag performances_path, method: :get do %>
    <div class="ro-search-bar-container wireframe" style="">
      <%= text_field_tag :query,
      params[:query],
      class: "ro-search-bar__bar ro-font-main",
      placeholder: "artist, genre, or location"
      %>
      <%= button_tag(type: "Search", class: "ro-search-bar__button") do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>
  <% end %>
  <!-- QR scan link within search container -->
  <%= render 'shared/qr_button', display_class: "wide-screen-buttons" %>
</div>

app/views/shared/_section_spacer.html.erb
<div class="ro-wrapper wireframe <%= background_color %>">
  <div class="ro-container wireframe <%= background_color %>" style="height: 50px;">
  </div>
</div>

app/views/shared/_user_options_button.html.erb
<!-- position relative square -->
<div class="wireframe ro-button-useroptions-outer-container <%= local_assigns[:display_class] %>" style="">
  <!-- position fixed square -->
  <div class="wireframe ro-button-useroptions-inner-container">
    <% if user_signed_in? %>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "ro-button-useroptions-avatar" %>
      <% else %>
        <div class="ro-navbar__user-login-icon-container">
          <i class="fas fa-user ro-navbar__user-login-icon" style=""></i>
        </div>
      <% end %>
      <div id="<%= local_assigns[:drop_menu_id] %>" class="ro-button-useroptions-cssdropdown-content">
        <%= link_to "Make an artist page", new_artist_path, class: "dropdown-item" %>
        <%= link_to "Post a performance", new_performance_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
      <!-- button is z-indexed above everything else and given 0 opacity -->
      <div id="<%= local_assigns[:drop_button_id] %>" class="ro-button-useroptions-cssdropbtn"></div>
    <% else %>
      <%= link_to new_user_session_path, class: "ro-navbar__user-login-icon-container wireframe", style: ""  do %>
        <i class="fas fa-user ro-navbar__user-login-icon" style=""></i>
      <% end %>
    <% end %>
  </div>
</div>