config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :performances, only: %i[index show new create] do
    resources :tips, only: %i[new create]
    resources :messages, only: %i[create]
  end

  resources :tips, only: :show do
    resources :payments, only: :new
  end

  resources :artists, only: %i[new create show]
  namespace :artist do
    resources :performances, only: %i[index show]
  end

end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :artist
  has_many :tips, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true
  validates :address, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def live?
    time = end_time - Time.now
    duration = end_time - start_time
    time.positive? && time <= duration
  end

  def live_today?
    start_time.day == Date.today.day && start_time.month == Date.today.month && start_time.year == Date.today.year
  end

  def upcoming?
    start_time > Time.now
  end

  def archived?
    end_time < Time.now
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def index
    @performances = policy_scope(Performance).order(created_at: :desc)
    if params[:query].present?
      @performances = @performances.where("address ILIKE ?", "%#{params[:query]}%")
    end

    @markers = @performances.geocoded.map do |performance|
      {
        lat: performance.latitude,
        lng: performance.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { performance: performance })
      }
    end

    @tips = Tip.all
    @artist_ranking = Artist.order_by_tips

    authorize @performances

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'performances/list', locals: { performances: @performances }, formats: [:html] }
    end
  end

  def show
    @performance = Performance.find(params[:id])
    @performance.tips.find(params['tip_id']).update(state: 'paid') if params['result'] == 'success'
    PerformanceChannel.broadcast_to(
      @performance,
      tip: render_to_string(partial: "tips/amount", locals: { amount: @performance.tips.where(state: "paid").sum(:amount_cents) })
    )
    @message = Message.new
    @performance.artist = @performance.artist
    @tip = Tip.new
    @messages = @performance.messages.order(created_at: :desc)
    tips = @performance.tips.where(state: "paid").order(created_at: :desc)
    # tips = @performance.tips.order(created_at: :desc)
    @messages_tips = (@messages + tips).sort_by(&:created_at).reverse
    authorize @performance
  end

  def new
    @performance = Performance.new
    authorize @performance
  end

  def create
    @performance = Performance.new(performance_params)
    authorize @performance
    if @artist = Artist.find_by(user_id: current_user.id)
      @performance.artist = @artist
      if @performance.save
        redirect_to performances_path
        return
      else
        render :new
      end
    else
      redirect_to performances_path, notice: "You must be an artist to perform this action"
    end
  end

  private

  def performance_params
    params.require(:performance).permit(:name, :description, :address, :start_time, :end_time)
  end

end

app/views/performances/_artist_ranking_table.html.erb
<td>
  <h6><%= artist.name %></h6>
</td>
<td>
  <h6>¥<%= artist.tips_total %></h6>
</td>
<td>
  <% performances = Performance.where(artist: artist) %>
  <% if performances.first.live? %>
    <%= link_to performance_path(performances.first) do %>
      <h6 class="live-button-red">LIVE</h6>
    <% end %>
  <% elsif performances.first.live_today? %>
    <%= link_to performance_path(performances.first) do %>
      <h6 class="live-button-blue">LIVE Today!</h6>
    <% end %>
  <% else %>
    <h6> <%= "    " %></h6>
  <% end %>
</td>

app/views/performances/_form.html.erb
<%= form_with url: performances_path, method: :get, html: { data: { test_target: "form" } } do %>
  <%= text_field_tag :query,
    params[:query],

    class: "form-control",
    data: {
          test_target: "input",
          action: "keyup->test#update"
        } %>

  <%= submit_tag "Search", class: "btn btn-ghost mt-2" %>
<% end %>

app/views/performances/_list.html.erb
<div data-test-target="list" class="card-row">
  <% @performances.each do |performance| %>
    <%# <div data-test-target="items" class=""> %>
    <%# <i class="far fa-heart"></i> %>
    <%= link_to performance_path(performance), class: "small-cards" do %>
      <% if performance.artist.photo.attached? %>
        <%= cl_image_tag performance.artist.photo.key, height: 300, width: 400, crop: :fill, class:"perf-card-sm" %>
      <% else %>
        <%= image_tag "https://miro.medium.com/max/1400/0*D2xr7G_v2nbI9eiB", height: 300, width: 400, crop: :fill, class:"perf-card-sm" %>
      <% end %>
      <div class="perf-text-sm wireframe">
        <p><strong><%= performance.artist.name %></strong></p>
        <p><em class="fas fa-map-marker-alt text-light"></em>  <%= performance.address %> </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/performances/_new_list.html.erb
<div data-test-target="list" class="performance-grid">
  <% @performances.each do |performance| %>
    <div class="performance-grid__item">
      <%= link_to performance_path(performance) do %>
        <div class="performance-grid__item-photo-container">
          <% if performance.artist.photo.attached? %>
            <%= cl_image_tag performance.artist.photo.key, height: 300, width: 400, crop: :fill, class: "photo-class" %>
          <% else %>
            <%= image_tag "https://miro.medium.com/max/1400/0*D2xr7G_v2nbI9eiB", crop: :fill, class: "photo-class" %>
          <% end %>
        </div>
        <div class="performance-grid__item-text-container">
          <%= link_to performance.artist.name, artist_path(performance.artist.id), class: "performance-text--name" %>
          <p><em class="fas fa-map-marker-alt text-light"></em><%= performance.address %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/performances/_theleftoutpartial.html.erb
  <%begin %>
  <%# Posting a perforance is a user journey for artists, and also I'll make this available in the user menu, so I'm commenting this button for now. Gareth %>
  <div class="ro-wrapper wireframe dark_purple_background">
    <div class="ro-container wireframe" style="">
      <div class="d-flex justify-content-end">
        <%= link_to "Post your performance", new_performance_path, class:"btn tip-btn w-75 btn-block" %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "Post your performance", new_performance_path, class:"btn tip-btn w-75 btn-block" %>
  </div>
<% end %>

app/views/performances/_tip_ranking.html.erb
<div data-controller="rankings" class="card-trip wireframe" style="width: 100%;">
  <h3 class="wireframe section-title" style="margin-left: -8px;">Artist Rankings</h3>
  <div class="show-button" data-action="click->rankings#reveal">
    <h6>Show all</h6>
  </div>
  <table class="table">
    <thead>
    </thead>
    <tbody>
      <% artist_ranking.first(3).each_with_index do |artist, index| %>
        <tr>
          <th scope="row">
            <h6><%= index + 1 %></h6>
          </th>
          <td>
            <h6><%= artist.name %></h6>
          </td>
          <td>
            <h6>¥<%= artist.tips_total %></h6>
          </td>
          <td>
            <% performances = Performance.where(artist: artist) %>
            <% if performances.last.live? %>
              <%= link_to performance_path(performances.first) do %>
                <h6 class="live-button-red">LIVE</h6>
              <% end %>
            <% elsif performances.last.live_today? %>
              <%= link_to performance_path(performances.first) do %>
                <h6 class="live-button-blue">LIVE Today!</h6>
              <% end %>
            <% else %>
              <h6> <%= "    " %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% artist_ranking[3..-1].each_with_index do |artist, index| %>
        <tr class="d-none" data-rankings-target="artist" data-action="click->rankings#showRankings">
          <th scope="row">
            <h6><%= index + 4 %></h6>
          </th>
          <td>
            <h6><%= artist.name %></h6>
          </td>
          <td>
            <h6>¥<%= artist.tips_total %></h6>
          </td>
          <td>
            <% performances = Performance.where(artist: artist) %>
            <% if performances.first.live? %>
              <%= link_to performance_path(performances.first) do %>
                <h6 class="live-button-red">LIVE</h6>
              <% end %>
            <% elsif performances.first.live_today? %>
              <%= link_to performance_path(performances.first) do %>
                <h6 class="live-button-blue">LIVE Today!</h6>
              <% end %>
            <% else %>
              <h6> <%= "    " %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/performances/index.html.erb
<div data-controller="test" class="">
  <!-- thin spacer white -->
  <div class="ro-wrapper wireframe white_background">
    <div class="ro-container wireframe white_background" style="height: 25px;">
    </div>
  </div>
  <!-- map title section -->
  <div class="ro-wrapper wireframe white_background">
    <div class="ro-container wireframe" style="">
      <h5 class="wireframe section-title background-color_text" style="width: 100%;"><strong><%= @performances.all.count %> upcoming performances in <%= params[:query].present? ? params[:query] : "Japan" %></strong></h5>
    </div>
  </div>
  <!-- map section ----- -->
  <div class="ro-wrapper wireframe"  style="flex-direction: column; position: relative;">
    <div class="overlay-wrapper">
      <div class="ro-container wireframe" style="">
        <div class="big-center-card" style="">
          <div id="map"
          style="width: 100%; height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
    <!-- background colors -->
    <div class="wrapper ro-wrapper home-halfscreen-upper half_and_half-wrapper white_background"  style=""></div>
    <div class="wrapper ro-wrapper home-halfscreen-lower half_and_half-wrapper main-color_background"  style=""></div>
  </div>
  <!-- spacer dark purple -->
  <%= render "shared/section_spacer", background_color: "dark_purple_background"  %>
  <!-- tip ranking -->
  <div class="ro-wrapper wireframe dark_purple_background">
    <div class="ro-container wireframe" style="justify-content: start;">
      <%= render "tip_ranking", artist_ranking: @artist_ranking %>
    </div>
  </div>
  <div class="ro-wrapper wireframe dark_purple_background">
    <div class="ro-container wireframe" style="justify-content: start;">
      <h3 class="wireframe section-title">Live today</h3>
    </div>
  </div>
  <!-- The New Owl Carousel-->
  <div class="ro-wrapper wireframe dark_purple_background">
    <div class="ro-container wireframe" style="justify-content: start;">
      <div id="owl-performances-index" class="photo-container my-3 owl-carousel owl-theme">
        <% one_performance = @performances.sample %>
        <% first_performance = @performances.first %>
        <% last_performance = @performances.last %>
        <% while [first_performance, last_performance].include?(one_performance) %>
          <% one_performance = @performances.sample %>
        <% end %>
        <!-- item 1 -->
        <div class="list1">
          <div class="upper-components">
            <i style="color: white" class="far fa-heart"></i>
            <div class="live-button">
              <p>LIVE</p>
            </div>
          </div>
          <%= link_to performance_path(one_performance) do %>
            <% if one_performance.artist.photo.attached? %>
              <%= cl_image_tag one_performance.artist.photo.key, height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% else %>
              <%= image_tag "https://miro.medium.com/max/1400/0*D2xr7G_v2nbI9eiB", height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% end %>
            <div class="perf-text mauve_background">
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <h5 class="live-now-card-text"><strong><%= one_performance.artist.name %></strong></h5>
                <p class="live-now-card-text"><em class="fas fa-map-marker-alt text-light"></em>  <%= one_performance.address %></p>
              </div>
              <p class="live-now-card-text"><strong><%= one_performance.name %></strong></p>
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <p class="live-now-card-text"><em class="far fa-calendar-alt"></em> <%= one_performance.start_time.strftime("%Y/%m/%d") %></p>
                <p class="live-now-card-text"><em class="far fa-clock"></em> <%= one_performance.start_time.strftime("%H:%M") %></p>
              </div>
            </div>
          <% end %>
        </div>
        <!-- item 2 -->
        <div class="list2">
          <%= link_to performance_path(first_performance) do %>
            <% if first_performance.artist.photo.attached? %>
              <%= cl_image_tag first_performance.artist.photo.key, height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% else %>
              <%= image_tag "https://miro.medium.com/max/1400/0*D2xr7G_v2nbI9eiB", height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% end %>
            <div class="perf-text mauve_background">
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <h5 class="live-now-card-text"><strong><%= first_performance.artist.name %></strong></h5>
                <p class="live-now-card-text"><em class="fas fa-map-marker-alt text-light"></em>  <%= one_performance.address %></p>
              </div>
              <p class="live-now-card-text"><strong><%= first_performance.name %></strong></p>
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <p class="live-now-card-text"><em class="far fa-calendar-alt"></em> <%= one_performance.start_time.strftime("%Y/%m/%d") %></p>
                <p class="live-now-card-text"><em class="far fa-clock"></em> <%= one_performance.start_time.strftime("%H:%M") %></p>
              </div>
            </div>
          <% end %>
        </div>
        <!-- item 3 -->
        <div class="list3">
          <%= link_to performance_path(last_performance) do %>
            <% if last_performance.artist.photo.attached? %>
              <%= cl_image_tag last_performance.artist.photo.key, height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% else %>
              <%= image_tag "https://miro.medium.com/max/1400/0*D2xr7G_v2nbI9eiB", height: 600, width: 800, crop: :fill, class:"perf-card-lg" %>
            <% end %>
            <div class="perf-text mauve_background">
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <h5 class="live-now-card-text"><strong><%= last_performance.artist.name %></strong></h5>
                <p class="live-now-card-text"><em class="fas fa-map-marker-alt text-light"></em>  <%= one_performance.address %></p>
              </div>
              <p class="live-now-card-text"><strong><%= last_performance.name %></strong></p>
              <div style="display: flex; flex-direction: row; justify-content: space-between;">
                <p class="live-now-card-text"><em class="far fa-calendar-alt"></em> <%= one_performance.start_time.strftime("%Y/%m/%d") %></p>
                <p class="live-now-card-text"><em class="far fa-clock"></em> <%= one_performance.start_time.strftime("%H:%M") %></p>
              </div>
            </div>
          <% end %>
        </div>
        <!-- end of carousel items -->
      </div>
    </div>
  </div>
</div>
<!-- spacer dark purple -->
<%= render "shared/section_spacer", background_color: "dark_purple_background"  %>
<!-- The Performances Index -->
<div class="ro-wrapper wireframe dark_purple_background">
  <div class="ro-container wireframe" style="">
    <h3 class="wireframe section-title">More shows coming up</h3>
  </div>
</div>
<div class="ro-wrapper wireframe dark_purple_background">
  <div class="ro-container wireframe" style="">
    <%#= render "list", performances: @performances %>
    <%= render "new_list", performances: @performances  %>
  </div>
</div>
</div>
</div>

app/views/performances/new.html.erb
<div class="ro-wrapper wireframe dark_purple_background">
  <div class="ro-container wireframe" style="">
    <h1>Post your show!</h1>
  </div>
</div>
<div class="ro-wrapper wireframe dark_purple_background">
  <div class="ro-container wireframe" style="">
    <div class="container">
      <%= simple_form_for @performance do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :start_time, as: :time, html5: true %>
        <%= f.input :end_time, html5: true %>
        <%= f.submit :Post, class:"btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/performances/show.html.erb
<!--Streaming part / photo part -->

<div class="ro-wrapper wireframe">
  <div class="ro-container wireframe">
    <div class="title-container">
      <div class="d-flex justify-content-between">
        <%= link_to artist_path(@performance.artist), class: "d-flex m-auto" do %>
          <% if @performance.artist.photo.attached?  %>
            <%= cl_image_tag @performance.artist.photo.key, class: "avatar-large" %>
          <% else %>
            <%= image_tag "https://www.aceshowbiz.com/images/photo/shakira.jpg", class:"avatar-large" %>
          <% end %>
        <% end %>
        <div style="display: flex flex-direction: column;">
          <div class="container d-flex align-content-center justify-content-around flex-column">
            <div class="d-flex bd-highlight">
              <h3 class="m-0 w-100 bd-highlight style="font-size: 24px;"><%= @performance.artist.name %></h3>
              <% if @performance.artist.user == current_user %>
                <%= link_to 'Edit', "/", class:'btn-performance flex-shrink-1 bd-highlight', style:'width: 110px; height:30px;' %>
              <% else %>
                <%= link_to 'Follow', "/", class:'btn-performance flex-shrink-1 bd-highlight', style:'width: 110px; height:30px;' %>
              <% end %>
            </div>
            <!-- stuff above -->
            <p class="m-0"><%= @performance.name %></p>
          </div>
          <!-- stuff below -->
          <div class="details pl-2" style="width: 260px;">
            <div class="mb-0 d-flex bd-highlight">
              <div class="pl-2 flex-grow-1 bd-highlight">
                <p><em class="fas fa-map-marker-alt text-light"></em> <%= @performance.address %></p>
              </div>
              <div class="pr-2 bd-highlight">
                <p><em class="mb-0 far fa-calendar-alt"></em> <%= @performance.start_time.strftime("%Y/%m/%d") %></p>
              </div>
              <div class="mb-0 bd-highlight">
                <p><em class="far fa-clock"></em> <%= @performance.start_time.strftime("%H:%M") %>- <%= @performance.end_time.strftime("%H:%M") %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="ro-wrapper wireframe">
  <div class="ro-container wireframe carousel-screenwidth-container">
    <div class="performance-photos ">
      <div class="tips-today wireframe" style="margin-left: 20px;">
        <p style="margin-bottom: 0px; margin-right: 10px; margin-top: 2px;">Tips</p>
        <%= render "tips/amount", amount: @performance.tips.where(state: "paid").sum(:amount_cents) %>
      </div>
      <div id="owl-one" class="photo-container mb-3 owl-carousel owl-theme ">
        <!--Carousel-->
        <% if @performance.photos.length > 0  %>
          <%= cl_image_tag @performance.photos[0].key, class: "performance-photo" %>
        <% else %>
          <%= image_tag "yoyogi2.jpg", class:"performance-photo" %>
        <% end %>
        <% if @performance.photos.length > 1  %>
          <%= cl_image_tag @performance.photos[1].key, class: "performance-photo" %>
        <% else %>
          <%= image_tag "yoyogi3.jpg", class:"performance-photo" %>
        <% end %>
        <% if @performance.photos.length > 2  %>
          <%= cl_image_tag @performance.photos[2].key, class: "performance-photo" %>
        <% else %>
          <%= image_tag "yoyogi-park-tokyo.jpg", class:"performance-photo" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Cards space-->
<!--Messages container-->
<div class="container">
  <div class="container message-container my-2 w-100" data-controller="display-messages" data-user-id="<%= current_user.id %>">
    <!--Extension messages area-->
    <div id="messages" class="container messages-content messages-content-large pl-1 pr-3" style="height:320px;" data-display-messages-target="box" data-performance-id="<%= @performance.id %>">
      <% if @messages_tips.length == 0 %>
        <p data-display-messages-target="placeholder" id="message-placeholder"><%= "Nothing to show yet" %></p>
      <% else %>
        <% @messages_tips.each do |element| %>
          <% if element.is_a?(Message) %>
            <%= render "messages/message", message: element %>
          <% else %>
            <%= render "tips/tip", tip: element %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <p data-display-messages-target="display" data-action="click->display-messages#display"> <%= "View #{@performance.messages.count + @performance.tips.count} more messages" unless @performance.messages.length < 2 %></p>
    <div class="msg-form">
      <%= simple_form_for [@performance, @message], remote: true do |f| %>
        <%= f.input :content, as: :string, placeholder: "Send message", label: false, input_html: { class:"input-color msg-box"} %>
        <div class="d-flex justify-content-end">
          <%= f.input :photo, as: :file, label: false, input_html: { class:"d-none"} do %>
            <i class="fas fa-camera btn input-color-btn"></i>
          <% end %>
          <%= f.button :button, input_html: { class:"btn-height"} do %>
            <i class="far fa-paper-plane input-color"></i>
          <% end %>
          <%# f.input :photo, as: :file, input_html: { class:'d-none'}, label_html: { class: 'btn ml-2', } %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--Messages box-->
<!-- songname displayer -->
<!-- views/performances/show.html.erb -->
<%= content_tag :div, class: "song_titles", id: "song_titles_array", data: {songs: @performance.songs, n: 0} do %>
<% end %>
<div class="ro-wrapper wireframe">
  <div class="ro-container wireframe">
    <% if @performance.artist.user == current_user %>
      <p id="change-the-song-buttton" class="btn profile-btn">song nav</p>
    <% else %>
    <% end %>
  </div>
</div>